name: gradle-clean-build-workflow

on:
  workflow_dispatch:
jobs:
  clean_build_job:
    name: clean_build_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project repository
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6

      - name: Execute Gradle clean and build
        run: ./gradlew clean build

      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: github-workflow-gradle-project-build-reports
          path: build/reports/